name: Simple CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Firefox Driver
        run: |
          GECKODRIVER_VERSION=`curl https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r .tag_name`
          wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          tar -xvzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/

      - name: Check formatting
        run: black .

      - name: Run tests
        run: make test

      - name: Check coverage
        run: coverage report --fail-under=60
